[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
toml = "0.5"
levenshtein = "1.0" 
rand = "0.8"
age = "0.8"
tar = "0.4"